"""
This is a setup.py script generated by py2app

Usage:
    python setup.py py2app
"""

from setuptools import setup
# === 新增：匯入 glob 函式來輕鬆尋找檔案 ===
from glob import glob

APP = ['screen_translator.py'] # <--- *** 請將 'your_script_name.py' 換成您自己的檔名 ***
APP_NAME = "APMLyrics" # <--- 您可以自訂應用程式的名稱

# === 新增：定義要包含的額外檔案 ===
# 格式為 [('目標資料夾', ['來源檔案1', '來源檔案2', ...])]
# 'assets/img' 是指在 App 包裹內的相對路徑
# glob('assets/img/*.png') 會自動找到 assets/img/ 資料夾下所有的 .png 檔案
DATA_FILES = [
    ('assets/img', glob('assets/img/*.png'))
]

# --- py2app 選項設定 ---
OPTIONS = {
    'argv_emulation': True,
    'packages': ['PIL'], 
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Monitors a specific window",
        'CFBundleIdentifier': "com.yourname.osx.windowmonitor",
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2025, Your Name, All Rights Reserved",
        'NSScreenCaptureDescription': 'This app needs to capture the screen to display the window preview.',
    }
}

# --- 主設定函式 ---
setup(
    app=APP,
    name=APP_NAME,
    # === 新增：將 DATA_FILES 設定加入打包程序 ===
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)